---
name: Test

on: 
  push:
    branches:
      - '**'

jobs:
  # Test YAML
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run yamllint
        shell: bash
        run: |
          sudo apt install yamllint
          $GITHUB_WORKSPACE/test/scripts/yamllint
...
