---
name: Test

on: 
  push:
    branches:
      - '**'

jobs:
  # Test documentation generation
  doxygen:
    runs-on: ubuntu-18.04
    container: johnmcfarlane/cnl_ci:base-21.10
    steps:
      - uses: actions/checkout@v2

      - name: Test Doxyfile
        shell: bash
        run: |
          doxygen -s -u doc/Doxyfile
          rm doc/Doxyfile.bak
          git diff --exit-code

      - name: Generate documentation
        shell: bash
        run: $GITHUB_WORKSPACE/doc/generate

      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ${{github.workspace}}/htdocs
...
